require: rt_rubocop_defaults

AllCops:
  TargetRubyVersion: 2.4
  SuggestExtensions: false

Metrics/LineLength:
  Max: 99
  Exclude:
    - test/*

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'

Metrics/AbcSize:
  Exclude:
    - test/*

Metrics/ClassLength:
  Exclude:
    - test/*

Metrics/MethodLength:
  Exclude:
    - test/*
